version: '3'
services:
    zookeeper:
        container_name: iris-zookeeper
        image: bitnami/zookeeper:latest
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        container_name: iris-kafka
        image: 'bitnami/kafka:latest'
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        volumes:
            - ./kafka/server.properties:/bitnami/kafka/config/server.properties
        environment:
            - BITNAMI_DEBUG=true
    secure-agent-graph:
        container_name: iris-sag
        environment:
            JAVA_OPTIONS: '-XX:MaxRAMPercentage=40.0'
            JWKS_URL: 'disabled'
        command:
            - --config
            - /fuseki/config/config.ttl
        image: iris/secure-agent-graph
        depends_on:
            - kafka
        ports:
            - 3030:3030
    transparent-proxy:
        container_name: iris-transparent-proxy
        image: iris-transparent-proxy
        ports:
            - 5013:80
        env_file:
            - './.env'
    api:
        container_name: iris-api
        image: iris-api
        ports:
            - 3010:5021
        env_file:
            - './.env'
