
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-visualiser
spec:
  selector:
    matchLabels:
      io.kompose.service: iris-visualiser
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/istio-ingress/sa/istio-ingress"]
      to:
        - operation:
            methods: ["GET","POST"]
      when:
       - key: request.auth.claims[groups]
         values:
             - iris_access