resources:
  - ../../base

namespace: iris

configMapGenerator:
  - name: iris-transparent-proxy-configs
    envs:
      - params.env


patches:

  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount


labels:
  - pairs:
      env: demo


images:
  - name: iris-transparent-proxy-image
    newName: 503561419905.dkr.ecr.eu-west-2.amazonaws.com/iris/transparent-proxy
    newTag: "1736292556"


