apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: transparent-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: iris-transparent-proxy
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: iris-transparent-proxy
    spec:
      serviceAccountName: iris-transparent-proxy-sa
      containers:
        - envFrom:
               - configMapRef:
                   name: iris-transparent-proxy-configs
               - secretRef:
                   name: iris-transparent-proxy-secrets


          image: iris-transparent-proxy-image
          livenessProbe:
            httpGet:
              path: /transparent-proxy/health
              port: 80
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: iris-transparent-proxy
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
