namespace: iris

resources:
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - istio/virtualService.yaml
  - istio/gateway.yaml
  - istio/preauthentication.yaml
  - istio/requestAuthentication.yaml
  - istio/authorizationpolicy/allow-ingress-to-iris-transparent-proxy.yaml
  - istio/authorizationpolicy/deny-by-default.yaml

labels:
  - pairs:
      app: iris-transparent-proxy
      env: ENV_PLACEHOLDER
      app.kubernetes.io/name: iris-transparent-proxy







