resources:
  - ../../base

namespace: iris

configMapGenerator:
  - name: iris-visualiser-configs
    envs:
      - params.env


patches:
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
labels:
  - pairs:
      env: prod
images:
  - name: iris-visualiser-image:template
    newName: xxxxxx.dkr.ecr.eu-west-2.amazonaws.com/iris/visualiser
    newTag: '1737626576'