apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: iris-transparent-proxy-static-secret
spec:
  refreshAfter: 30s

  # path of the secret
  path: applications/iris/transparent-proxy

  type: kv-v2

  mount: k8-cluster

  destination:
    # dest k8s secret
    name: iris-static-secret
    create: true

  vaultAuthRef: iris-transparent-proxy-vault-auth
