apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paralog-python-api-static-secret
spec:
  refreshAfter: 30s

  # path of the secret
  path: applications/paralog/paralog-python-api

  type: kv-v2

  mount: k8-cluster

  destination:
    # dest k8s secret
    name: paralog-python-api-static-secret
    create: true

  vaultAuthRef: paralog-python-api-static-auth
