export enum RoofInsulation {
  RaftersRoofInsulation = 'Rafters Roof Insulation',
  JoistsRoofInsulation = 'Joists Roof Insulation',
  CeilingInsulation = 'Ceiling Insulation',
  FlatRoofInsulation = 'Flat Roof Insulation',
  SlopingCeilingRoofInsulation = 'Sloping Ceiling Roof Insulation',
  AssumedNoInsulation = 'Assumed No Insulation',
  AssumedLoftInsulation = 'Assumed Loft Insulation',
  LoftInsulation = 'Loft Insulation',
  AssumedLimitedInsulation = 'Assumed Limited Insulation',
  LimitedInsulation = 'Limited Insulation',
  InsulatedAssumed = 'Insulated Assumed',
  NoInsulationAssumed = 'No Insulation Assumed',
  ThatchedWithAdditionalRoofInsulation = 'Thatched With Additional Roof Insulation',
}
