name: Continuous Integration & Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
  deploy-dev:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    needs: [lint]
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          ENV: 'dev'
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
      - name: Create environment file
        run: npm run config
        env:
          ENV: 'dev'
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
      - name: Build
        run: npm run build:dev
      - name: Deploy to development
        run: |
          aws s3 sync ./dist/c477-vis s3://${{ secrets.S3_BUCKET }}
